### ISSUE TITLE
move msg

### ISSUE THREAD

**Issue by trikiman** [laralove143/interchannel-message-mover#10] opened 2022-11-30 02:18 UTC
u cant move msg twice. its just removed. and it is sad.

**Comment by laralove143** [comment] 2022-12-03 15:22
is this a duplicate of #12

**Comment by trikiman** [comment] 2022-12-04 15:33
no this is other one. its mean u can move twice. its just dissapear.

**Comment by laralove143** [comment] 2022-12-05 21:40
What do you mean? I don't understand

**Comment by trikiman** [comment] 2022-12-06 15:08
if u move msg 1 time to other channel all good, but if u move it again its just disappears.

**Comment by laralove143** [comment] 2022-12-07 16:49
You mean moving the same message twice?

**Comment by laralove143** [comment] 2022-12-10 19:07
That's included in #9

**Closed by laralove143** 2022-12-10 19:07 UTC
